### ISSUE TITLE
Theme - Default

### ISSUE THREAD

**Issue by kh0p** [karminski/EVA-theme#2]
Settings for sidebar etc.

**Comment by karminski** [comment]
Oh sorry, I will rewrite it later. This theme is too dazzling to watch.

**Comment by karminski** [comment]
@defm03 Hi, it's done. I still can't work with this theme long time. 55555

**Comment by kh0p** [comment]
Arigatou senpai!

**Comment by karminski** [comment]
（<ゝω·）kira~☆
